### ISSUE TITLE
vgo2nix hangs if the repository has more than a hundred dependency

### ISSUE THREAD

**Issue by kalbasit** [adisbladis/vgo2nix#16]
https://github.com/adisbladis/vgo2nix/blob/f2694cd352830f0561bc00bbcaa08cefb2e36439/main.go#L181-L193

I was trying to package [jx](https://github.com/jenkins-x/jx) which has about a 1000 entries in the go.sum and for some reason, vgo2nix was hanging. After some code review I figured out what's going on:

1. `jobs` and `resuts` are both buffered channels with a capacity of 100. Line 181-182
2. A loop over the entries (for jx, that's a loop over a 1000 items), it sends one entry at a time to the workers through the `jobs` buffered channel. After the first 100 entries, it waits until it has the capacity to take more.
3. The capacity of the `jobs` channel is essential determined by the workers we have and workers are able to take more jobs only if their result was read.
4. The worker result is read on line 193.

Essentially, since we do not read the results until we send all the entries to the workers, and we send then entries in an inline loop, the main go-routine never reaches line 193 and it gets stuck forever.

A simple fix would be to move the for loop below to another goroutine, and wait globally for all goroutines to come back using a `sync.WaitGroup`

https://github.com/adisbladis/vgo2nix/blob/f2694cd352830f0561bc00bbcaa08cefb2e36439/main.go#L187-L189

**Comment by collinwright** [comment]
This prevents vgo2nix from building github.com/concourse/concourse

**Comment by adisbladis** [comment]
I made a hackier solution for now (just set buffer size to `len(entries)` since it was much quicker to implement.
Using a `sync.WaitGroup` is probably nicer.

**Comment by kalbasit** [comment]
56ac56bb0d969aa1c3830aba98e4d912366c2261 is good enough to unblock people, but will not scale very well on smaller machines.
