### ISSUE TITLE
Combine with https://github.com/kwohlfahrt/gomod2nix

### ISSUE THREAD

**Issue by kwohlfahrt** [adisbladis/vgo2nix#2]
I made a similar project when this didn't support native go modules: https://github.com/kwohlfahrt/gomod2nix.

I think the only thing that is really different is that it does fetching in parallel, and prints to stdout instead of `deps.nix`. It also gets the list of dependencies differently, so it can be passed an arbitrary directory to look for modules in. Let me know if you'd like to merge any of it and I'll put together a PR.

**Comment by adisbladis** [comment]
I'm more than open to accept patches to incorporate features from `gomod2nix`!

The change to print to stdout instead of `deps.nix` and the arbitrary directories is something I would want to have flags for while keeping the current default behaviour.

**Comment by adisbladis** [comment]
I have created 2 related issues with the actionable parts of this issue.
Feel free to create more issues with anything I've missed.
