### ISSUE TITLE
What license if vgo2nix under?

### ISSUE THREAD

**Issue by hartzell** [adisbladis/vgo2nix#24]
I'm doing something similar for [Spack](https://spack.io) and after reading through vgo2nix there are big hunks that I can just reuse (assuming you're willing).  What license is it published under?

Can you add a LICENSE file?

**Comment by adisbladis** [comment]
The license is documented in the nix expression: https://github.com/adisbladis/vgo2nix/blob/master/default.nix#L30

I should add a LICENSE too to make it more easily discoverable through github.

**Comment by hartzell** [comment]
Thanks!  Search showed me that, but my brain short-circuited and I thought it was being used for the package descriptions that the tool writes.
